spring:
  application:
    name: @project.name@
  mvc:
    servlet:
      path: /api/v1
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:fibank
    username: sa
    password: password
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables:
            autocommit: true
  liquibase:
    change-log: classpath:config/liquibase/db.changelog-master.yaml

fib:
  api:
    key: f9Uie8nNf112hx8s