databaseChangeLog:
  - changeSet:
      id: 1
      author: "admin"
      context: dev
      changes:
        - insert:
            tableName: cashiers
            columns:
              - column:
                  name: id
                  valueNumeric: 1
              - column:
                  name: name
                  value: MARTINA
        - insert:
            tableName: balances
            columns:
              - column:
                  name: id
                  valueNumeric: 1
              - column:
                  name: amount
                  value: 1000
              - column:
                  name: currency
                  valueNumeric: 0
              - column:
                  name: cashier_id
                  valueNumeric: 1
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 50
              - column:
                  name: denomination
                  value: 10
              - column:
                  name: balance_id
                  valueNumeric: 1
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 10
              - column:
                  name: denomination
                  value: 50
              - column:
                  name: balance_id
                  valueNumeric: 1
        - insert:
            tableName: balances
            columns:
              - column:
                  name: id
                  valueNumeric: 2
              - column:
                  name: amount
                  value: 2000
              - column:
                  name: currency
                  valueNumeric: 1
              - column:
                  name: cashier_id
                  valueNumeric: 1
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 100
              - column:
                  name: denomination
                  value: 10
              - column:
                  name: balance_id
                  valueNumeric: 2
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 20
              - column:
                  name: denomination
                  value: 50
              - column:
                  name: balance_id
                  valueNumeric: 2

        - insert:
            tableName: cashiers
            columns:
              - column:
                  name: id
                  valueNumeric: 2
              - column:
                  name: name
                  value: PETER
        - insert:
            tableName: balances
            columns:
              - column:
                  name: id
                  valueNumeric: 3
              - column:
                  name: amount
                  value: 1000
              - column:
                  name: currency
                  valueNumeric: 0
              - column:
                  name: cashier_id
                  valueNumeric: 2
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 50
              - column:
                  name: denomination
                  value: 10
              - column:
                  name: balance_id
                  valueNumeric: 3
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 10
              - column:
                  name: denomination
                  value: 50
              - column:
                  name: balance_id
                  valueNumeric: 3
        - insert:
            tableName: balances
            columns:
              - column:
                  name: id
                  valueNumeric: 4
              - column:
                  name: amount
                  value: 2000
              - column:
                  name: currency
                  valueNumeric: 1
              - column:
                  name: cashier_id
                  valueNumeric: 2
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 100
              - column:
                  name: denomination
                  value: 10
              - column:
                  name: balance_id
                  valueNumeric: 4
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 20
              - column:
                  name: denomination
                  value: 50
              - column:
                  name: balance_id
                  valueNumeric: 4

        - insert:
            tableName: cashiers
            columns:
              - column:
                  name: id
                  valueNumeric: 3
              - column:
                  name: name
                  value: LINDA
        - insert:
            tableName: balances
            columns:
              - column:
                  name: id
                  valueNumeric: 5
              - column:
                  name: amount
                  value: 1000
              - column:
                  name: currency
                  valueNumeric: 0
              - column:
                  name: cashier_id
                  valueNumeric: 3
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 50
              - column:
                  name: denomination
                  value: 10
              - column:
                  name: balance_id
                  valueNumeric: 5
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 10
              - column:
                  name: denomination
                  value: 50
              - column:
                  name: balance_id
                  valueNumeric: 5
        - insert:
            tableName: balances
            columns:
              - column:
                  name: id
                  valueNumeric: 6
              - column:
                  name: amount
                  value: 2000
              - column:
                  name: currency
                  valueNumeric: 1
              - column:
                  name: cashier_id
                  valueNumeric: 3
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 100
              - column:
                  name: denomination
                  value: 10
              - column:
                  name: balance_id
                  valueNumeric: 6
        - insert:
            tableName: denominations
            columns:
              - column:
                  name: quantity
                  value: 20
              - column:
                  name: denomination
                  value: 50
              - column:
                  name: balance_id
                  valueNumeric: 6
