databaseChangeLog:
  - changeSet:
      id: 1
      author: "admin"
      changes:
        - createTable:
            tableName: cashiers
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(150)
                  constraints:
                    nullable: false
  - changeSet:
      id: 2
      author: "admin"
      changes:
        - createTable:
            tableName: accounts
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: balance
                  type: DECIMAL(19, 2)
                  constraints:
                    nullable: false
              - column:
                  name: currency
                  type: VARCHAR(3)
                  constraints:
                    nullable: false
              - column:
                  name: cashier_id
                  type: BIGINT
                  constraints:
                    foreignKeyName: fk_cashier_account
                    references: cashiers(id)
                    nullable: false