databaseChangeLog:
  - changeSet:
      id: 1
      author: "admin"
      changes:
        - createTable:
            tableName: cashiers
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(150)
                  constraints:
                    nullable: false
  - changeSet:
      id: 2
      author: "admin"
      changes:
        - createTable:
            tableName: balances
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: amount
                  type: INT
                  constraints:
                    nullable: false
              - column:
                  name: currency
                  type: SMALLINT
                  constraints:
                    nullable: false
              - column:
                  name: cashier_id
                  type: BIGINT
                  constraints:
                    foreignKeyName: fk_cashier_balance
                    references: cashiers(id)
                    nullable: false
  - changeSet:
      id: 3
      author: "admin"
      changes:
        - createTable:
            tableName: denominations
            columns:
              - column:
                  name: denomination
                  type: INTEGER
              - column:
                  name: quantity
                  type: INTEGER
              - column:
                  name: balance_id
                  type: BIGINT
                  constraints:
                    foreignKeyName: fk_denomination_balance
                    references: balances(id)
                    nullable: false